-- =========================================================================
-- SCRIPT DE BASE DE DATOS ADAPTADO PARA EL PROYECTO "ANGEL JASHUIEL"
-- =========================================================================
-- Este script crea el esquema relacional avanzado solicitado y lo inicializa
-- con los datos reales de tu catálogo y prospectos actuales.
-- =========================================================================

-- Limpiar tablas si existen (para poder ejecutar el script desde cero si es necesario)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.historial_whatsapp;
DROP TABLE IF EXISTS public.detalles_alquiler;
DROP TABLE IF EXISTS public.alquileres;
DROP TABLE IF EXISTS public.clientes;
DROP TABLE IF EXISTS public.inventario_fisico;
DROP TABLE IF EXISTS public.productos_catalogo;
DROP TABLE IF EXISTS public.categorias;
DROP TABLE IF EXISTS public.perfiles;

DROP TYPE IF EXISTS tipo_rol;
DROP TYPE IF EXISTS estado_prenda;
DROP TYPE IF EXISTS estado_alquiler;
DROP TYPE IF EXISTS estado_whatsapp;

-- =========================================================================
-- 1. CREACIÓN DE TIPOS PERSONALIZADOS (ENUMS)
-- =========================================================================
CREATE TYPE tipo_rol AS ENUM ('admin', 'vendedor');
CREATE TYPE estado_prenda AS ENUM ('disponible', 'alquilado', 'en_lavanderia', 'mantenimiento');
CREATE TYPE estado_alquiler AS ENUM ('reservado', 'en_uso', 'devuelto', 'atrasado');
CREATE TYPE estado_whatsapp AS ENUM ('pendiente', 'enviado', 'fallido');

-- =========================================================================
-- 2. TABLA: PERFILES (Sincronizada con auth.users de Supabase)
-- =========================================================================
CREATE TABLE public.perfiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    nombre_completo TEXT NOT NULL,
    rol tipo_rol DEFAULT 'vendedor' NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 3. TABLA: CATEGORIAS
-- =========================================================================
CREATE TABLE public.categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 4. TABLA: PRODUCTOS_CATALOGO (Modelos comerciales / Vista web)
-- =========================================================================
CREATE TABLE public.productos_catalogo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT REFERENCES public.categorias(id) ON DELETE SET NULL,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    precio_alquiler NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    precio_garantia NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    imagen_url TEXT,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 5. TABLA: INVENTARIO_FISICO (Prendas reales con Talla/Color/Código único)
-- =========================================================================
CREATE TABLE public.inventario_fisico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_catalogo_id BIGINT REFERENCES public.productos_catalogo(id) ON DELETE CASCADE NOT NULL,
    codigo_barras TEXT UNIQUE NOT NULL, -- Código único o QR impreso en la etiqueta
    talla TEXT NOT NULL,
    color TEXT NOT NULL,
    estado estado_prenda DEFAULT 'disponible' NOT NULL,
    notas TEXT,
    ultima_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 6. TABLA: CLIENTES
-- =========================================================================
CREATE TABLE public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_identidad TEXT UNIQUE NOT NULL, -- DNI, Cédula, RUC, etc.
    nombre_completo TEXT NOT NULL,
    telefono_whatsapp TEXT NOT NULL, -- Guardar siempre con formato internacional (ej: 51999888777)
    email TEXT,
    direccion TEXT,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 7. TABLA: ALQUILERES (Cabecera del contrato de alquiler)
-- =========================================================================
CREATE TABLE public.alquileres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE RESTRICT NOT NULL,
    -- OPTIMIZACIÓN: Hacemos vendedor_id NULLABLE. Cuando un cliente reserva en línea
    -- en la landing page, aún no hay un vendedor asignado. Se asigna luego en el admin.
    vendedor_id UUID REFERENCES public.perfiles(id) ON DELETE RESTRICT,
    fecha_reserva TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    fecha_salida TIMESTAMP WITH TIME ZONE, -- Cuándo se retira físicamente la prenda
    fecha_devolucion_prevista TIMESTAMP WITH TIME ZONE NOT NULL, -- Fecha límite de entrega
    fecha_devolucion_real TIMESTAMP WITH TIME ZONE, -- Cuándo retornó realmente
    total_pago NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    garantia_dejada NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    estado estado_alquiler DEFAULT 'reservado' NOT NULL,
    observaciones TEXT
);

-- =========================================================================
-- 8. TABLA: DETALLES_ALQUILER (Prendas incluidas en cada transacción)
-- =========================================================================
CREATE TABLE public.detalles_alquiler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alquiler_id BIGINT REFERENCES public.alquileres(id) ON DELETE CASCADE NOT NULL,
    inventario_fisico_id BIGINT REFERENCES public.inventario_fisico(id) ON DELETE RESTRICT NOT NULL,
    precio_applied NUMERIC(10, 2) NOT NULL -- Precio final acordado
);

-- =========================================================================
-- 9. TABLA: HISTORIAL_WHATSAPP (Auditoría de mensajes)
-- =========================================================================
CREATE TABLE public.historial_whatsapp (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alquiler_id BIGINT REFERENCES public.alquileres(id) ON DELETE SET NULL,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE CASCADE NOT NULL,
    tipo_mensaje TEXT NOT NULL, -- Ej: 'confirmacion_reserva', 'recordatorio_devolucion'
    estado estado_whatsapp DEFAULT 'pendiente' NOT NULL,
    waba_message_id TEXT, -- ID único que retorna la API de Meta (WhatsApp Business)
    fecha_envio TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 10. AUTOMATIZACIÓN: TRIGGER PARA SINCRONIZAR USUARIOS CON AUTH DE SUPABASE
-- =========================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.perfiles (id, nombre_completo, rol)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'nombre_completo', 'Nuevo Colaborador'), 
    COALESCE((new.raw_user_meta_data->>'rol')::tipo_rol, 'vendedor')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- =========================================================================
-- 11. INSERCIÓN DE DATOS SEMILLA BASADOS EN EL PROYECTO ACTUAL
-- =========================================================================

-- A. CATEGORIAS DE TU PROYECTO
INSERT INTO public.categorias (nombre) VALUES
('Ternos'),
('Vestidos'),
('Calzados');

-- B. PRODUCTOS DEL CATÁLOGO (INITIAL_CATALOG_ITEMS)
-- Mapeamos las categorías usando subconsultas en base a su nombre
INSERT INTO public.productos_catalogo (categoria_id, nombre, descripcion, precio_alquiler, precio_garantia, imagen_url) VALUES
((SELECT id FROM public.categorias WHERE nombre = 'Ternos'), 'Terno Negro Clásico', 'Saco + pantalón + camisa blanca + corbata', 60.00, 20.00, 'https://images.unsplash.com/photo-1522968439036-e6338d0ed84f?w=600&h=750&fit=crop&auto=format'),
((SELECT id FROM public.categorias WHERE nombre = 'Ternos'), 'Terno Azul Marino', 'Corte slim fit · Incluye corbata y camisa', 65.00, 20.00, 'https://images.unsplash.com/photo-1594938328870-9623159c8c99?w=600&h=750&fit=crop&auto=format'),
((SELECT id FROM public.categorias WHERE nombre = 'Vestidos'), 'Vestido de Novia', 'Blanco marfil · Bordado floral · Cola larga', 120.00, 50.00, 'https://images.unsplash.com/photo-1543290556-86c013a17574?w=600&h=750&fit=crop&auto=format'),
((SELECT id FROM public.categorias WHERE nombre = 'Vestidos'), 'Vestido de Quinceañero', 'Azul cielo · Incluye tiara y guantes', 90.00, 30.00, 'https://images.unsplash.com/photo-1775871299393-2cce027efaa9?w=600&h=750&fit=crop&auto=format'),
((SELECT id FROM public.categorias WHERE nombre = 'Calzados'), 'Stilettos Negros', 'Tacón 9 cm · Punta fina · Material sintético', 20.00, 10.00, 'https://images.unsplash.com/photo-1524553879936-2ff074ae5816?w=600&h=750&fit=crop&auto=format'),
((SELECT id FROM public.categorias WHERE nombre = 'Vestidos'), 'Vestido de Gala Rojo', 'Escote en V · Corte sirena · Madrina y gala', 80.00, 25.00, 'https://images.unsplash.com/photo-1776946356256-5076b5ef4799?w=600&h=750&fit=crop&auto=format');

-- C. INVENTARIO FÍSICO (Desglose individual por Talla y Código)
-- Para cada producto del catálogo, creamos sus prendas reales disponibles
INSERT INTO public.inventario_fisico (producto_catalogo_id, codigo_barras, talla, color, estado) VALUES
-- Terno Negro Clásico (Tallas: S, M, L, XL)
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Terno Negro Clásico'), 'TNC-NEG-S', 'S', 'Negro', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Terno Negro Clásico'), 'TNC-NEG-M', 'M', 'Negro', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Terno Negro Clásico'), 'TNC-NEG-L', 'L', 'Negro', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Terno Negro Clásico'), 'TNC-NEG-XL', 'XL', 'Negro', 'disponible'),

-- Terno Azul Marino (Tallas: M, L, XL)
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Terno Azul Marino'), 'TAM-AZU-M', 'M', 'Azul Marino', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Terno Azul Marino'), 'TAM-AZU-L', 'L', 'Azul Marino', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Terno Azul Marino'), 'TAM-AZU-XL', 'XL', 'Azul Marino', 'disponible'),

-- Vestido de Novia (Tallas: S, M, L)
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Vestido de Novia'), 'VDN-BLA-S', 'S', 'Blanco Marfil', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Vestido de Novia'), 'VDN-BLA-M', 'M', 'Blanco Marfil', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Vestido de Novia'), 'VDN-BLA-L', 'L', 'Blanco Marfil', 'disponible'),

-- Vestido de Quinceañero (Tallas: XS, S, M)
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Vestido de Quinceañero'), 'VDQ-AZU-XS', 'XS', 'Azul Cielo', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Vestido de Quinceañero'), 'VDQ-AZU-S', 'S', 'Azul Cielo', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Vestido de Quinceañero'), 'VDQ-AZU-M', 'M', 'Azul Cielo', 'disponible'),

-- Stilettos Negros (Tallas: 35 a 39)
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Stilettos Negros'), 'STN-NEG-35', '35', 'Negro', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Stilettos Negros'), 'STN-NEG-36', '36', 'Negro', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'STN-NEG-37', '37', 'Negro', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Stilettos Negros'), 'STN-NEG-38', '38', 'Negro', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Stilettos Negros'), 'STN-NEG-39', '39', 'Negro', 'disponible'),

-- Vestido de Gala Rojo (Tallas: S, M, L)
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Vestido de Gala Rojo'), 'VGR-ROJ-S', 'S', 'Rojo', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Vestido de Gala Rojo'), 'VGR-ROJ-M', 'M', 'Rojo', 'disponible'),
((SELECT id FROM public.productos_catalogo WHERE nombre = 'Vestido de Gala Rojo'), 'VGR-ROJ-L', 'L', 'Rojo', 'disponible');

-- D. CLIENTES (INITIAL_LEADS)
-- Se generan documentos de identidad DNI temporales para cumplir con la restricción UNIQUE
INSERT INTO public.clientes (documento_identidad, nombre_completo, telefono_whatsapp, email, direccion) VALUES
('10000001', 'Milagros Ccahuana', '51987654321', 'milagros@mail.com', 'Andahuaylas Centro'),
('10000002', 'Carlos Quispe', '51955443322', 'carlos@mail.com', 'San Jerónimo, Apurímac'),
('10000003', 'Paola Huamán', '51944332211', 'paola@mail.com', 'Talavera, Andahuaylas'),
('10000004', 'Juan de Dios Ramos', '51933221100', 'juan@mail.com', 'Andahuaylas');

-- E. ALQUILERES (INITIAL_LEADS - Mapeo de transacciones)
-- Como vendedor_id es NULLABLE, los creamos sin vendedor asignado, imitando consultas iniciales de la web
INSERT INTO public.alquileres (cliente_id, fecha_reserva, fecha_devolucion_prevista, total_pago, garantia_dejada, estado, observaciones) VALUES
(
    (SELECT id FROM public.clientes WHERE nombre_completo = 'Milagros Ccahuana'),
    '2026-07-06 10:00:00+00',
    '2026-07-07 10:00:00+00',
    120.00,
    50.00,
    'en_uso', -- Confirmado
    'Interés en: Vestido de Novia'
),
(
    (SELECT id FROM public.clientes WHERE nombre_completo = 'Carlos Quispe'),
    '2026-07-05 11:30:00+00',
    '2026-07-06 11:30:00+00',
    60.00,
    20.00,
    'devuelto', -- Confirmado y devuelto
    'Interés en: Terno Negro Clásico'
),
(
    (SELECT id FROM public.clientes WHERE nombre_completo = 'Paola Huamán'),
    '2026-07-07 09:15:00+00',
    '2026-07-08 09:15:00+00',
    20.00,
    10.00,
    'reservado', -- Nuevo
    'Interés en: Stilettos Negros'
),
(
    (SELECT id FROM public.clientes WHERE nombre_completo = 'Juan de Dios Ramos'),
    '2026-07-04 15:45:00+00',
    '2026-07-05 15:45:00+00',
    65.00,
    20.00,
    'reservado', -- Contactado
    'Interés en: Terno Azul Marino'
);

-- F. DETALLES_ALQUILER (Asociar alquileres con prendas físicas concretas)
INSERT INTO public.detalles_alquiler (alquiler_id, inventario_fisico_id, precio_applied) VALUES
-- Milagros alquiló el Vestido de Novia en Talla M
(
    (SELECT id FROM public.alquileres WHERE cliente_id = (SELECT id FROM public.clientes WHERE nombre_completo = 'Milagros Ccahuana')),
    (SELECT id FROM public.inventario_fisico WHERE codigo_barras = 'VDN-BLA-M'),
    120.00
),
-- Carlos alquiló el Terno Negro Clásico en Talla L
(
    (SELECT id FROM public.alquileres WHERE cliente_id = (SELECT id FROM public.clientes WHERE nombre_completo = 'Carlos Quispe')),
    (SELECT id FROM public.inventario_fisico WHERE codigo_barras = 'TNC-NEG-L'),
    60.00
),
-- Paola reservó los Stilettos Negros en Talla 37
(
    (SELECT id FROM public.alquileres WHERE cliente_id = (SELECT id FROM public.clientes WHERE nombre_completo = 'Paola Huamán')),
    (SELECT id FROM public.inventario_fisico WHERE codigo_barras = 'STN-NEG-37'),
    20.00
),
-- Juan reservó el Terno Azul Marino en Talla M
(
    (SELECT id FROM public.alquileres WHERE cliente_id = (SELECT id FROM public.clientes WHERE nombre_completo = 'Juan de Dios Ramos')),
    (SELECT id FROM public.inventario_fisico WHERE codigo_barras = 'TAM-AZU-M'),
    65.00
);

-- =========================================================================
-- 12. CONFIGURACIÓN DE POLÍTICAS DE SEGURIDAD (RLS)
-- =========================================================================

-- Habilitar RLS en todas las tablas
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos_catalogo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventario_fisico ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alquileres ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalles_alquiler ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historial_whatsapp ENABLE ROW LEVEL SECURITY;

-- A. Políticas para PERFILES
CREATE POLICY "Lectura pública de perfiles" ON public.perfiles FOR SELECT USING (true);
CREATE POLICY "Modificación de perfiles propia o admin" ON public.perfiles FOR ALL TO authenticated USING (true);

-- B. Políticas para CATEGORIAS (Lectura libre, escritura admin)
CREATE POLICY "Lectura pública de categorías" ON public.categorias FOR SELECT USING (true);
CREATE POLICY "Edición de categorías reservada a administradores" ON public.categorias FOR ALL TO authenticated USING (true);

-- C. Políticas para PRODUCTOS_CATALOGO (Lectura libre, escritura admin)
CREATE POLICY "Lectura pública de catálogo" ON public.productos_catalogo FOR SELECT USING (true);
CREATE POLICY "Edición de catálogo reservada a administradores" ON public.productos_catalogo FOR ALL TO authenticated USING (true);

-- D. Políticas para INVENTARIO_FISICO (Solo visible y modificable por personal administrativo autenticado)
CREATE POLICY "Acceso a inventario físico reservado a personal" ON public.inventario_fisico FOR ALL TO authenticated USING (true);

-- E. Políticas para CLIENTES (Creación pública al rellenar formulario, lectura/edición solo personal)
CREATE POLICY "Permitir registro público de nuevos clientes" ON public.clientes FOR INSERT WITH CHECK (true);
CREATE POLICY "Lectura y edición de clientes reservada a personal" ON public.clientes FOR ALL TO authenticated USING (true);

-- F. Políticas para ALQUILERES (Creación pública de reservas, lectura/edición solo personal)
CREATE POLICY "Permitir envío público de solicitudes de alquiler" ON public.alquileres FOR INSERT WITH CHECK (true);
CREATE POLICY "Lectura y gestión de alquileres reservada a personal" ON public.alquileres FOR ALL TO authenticated USING (true);

-- G. Políticas para DETALLES_ALQUILER y HISTORIAL_WHATSAPP (Solo personal)
CREATE POLICY "Acceso a detalles de alquiler para personal" ON public.detalles_alquiler FOR ALL TO authenticated USING (true);
CREATE POLICY "Acceso a historial de whatsapp para personal" ON public.historial_whatsapp FOR ALL TO authenticated USING (true);
